### ISSUE TITLE
Add an ID to the table so styles can be applied

### ISSUE THREAD

**Issue by kjcoop** [MZAWeb/business-hours-plugin#22]
I added id="business_hours_table" to views/table.php. Line 8 now reads:
    <table id="business_hours_table" width='100%'>

It would be nice if this could be added to the code so if there's an upgrade, I don't have to go back in and add it again. Thank you!

**Comment by MZAWeb** [comment]
Hey, sorry for the delay. Was on vacations. I'll add it and release in the next version.
