### ISSUE TITLE
problems with hours

### ISSUE THREAD

**Issue by elmarduk** [MZAWeb/business-hours-plugin#24]
Setting for a work day: Mon open 09:00 to 21:00; 

Is it possible to show an image when (well its posible now, code below) but the question is; 

The problem is after 21:01 when the widget is still showing "Open". how I can resolve this problem?,

or for now it's not possible. 

OPEN
span class='working_hours_open'>Desde {{Open}}</span> hasta  <span class='working_hours_close'>{{Close}}</span

img class="aligncenter size-medium wp-image-5335" alt="delivery_area" src="IMAGE.png" width="1" height="1" />
![workho](https://f.cloud.github.com/assets/3670134/185303/6a17eda6-7d01-11e2-9c4d-5e6dcf834136.png)

**Comment by MZAWeb** [comment]
Hey, for now the open/close status is by day. I'll probably implement in the future a filter to allow people to customize the widget after the closing hours / before the opening.

Thanks

**Comment by elmarduk** [comment]
Thank's for you answer, tenia miedo que fuera eso but thank's again.
