### ISSUE TITLE
Afternoon Opening Time

### ISSUE THREAD

**Issue by kcurtis113** [MZAWeb/business-hours-plugin#28]
Is there a way to display an afternoon opening time? I have a client that opens at 1PM on Sundays and it is showing as 1AM.

**Comment by MZAWeb** [comment]
The open/close fields are free text, how come it's showing it as AM?

**Comment by kcurtis113** [comment]
No clue. I tried typing in "1 PM" and it displays as "1 PMam"

**Comment by kcurtis113** [comment]
I downloaded the zip and uploaded it and it's fine now. I have no clue what it was doing before!

**Comment by MZAWeb** [comment]
Cool. Maybe someone modified the code?
