### ISSUE TITLE
Getting rid of displaying the day of today with the opening hours

### ISSUE THREAD

**Issue by mokola** [MZAWeb/business-hours-plugin#29]
I would like to get rid form displaying the actual day with its opening hours. Any solution for that?

**Comment by cheeselouise** [comment]
This is important for me to know too. Please will someone respond?

**Comment by MZAWeb** [comment]
What exactly you guys want to show? How would your ideal functionality be?

**Comment by cheeselouise** [comment]
Hey thanks, 

I just want the opening times to go away and just show the table - so where it says 10 - 6 under SUMMER HOURS - I want to remove that. 

SUMMER HOURS

10 - 6
Day Open    Close
Monday  10  6
Tuesday 10  6
Wednesday   10  6
Thursday    10  6
Friday  10  6
Saturday    9   5
Sunday  Closed

**Comment by MZAWeb** [comment]
So, maybe I don't get it... but if you clean all the templates for that widget (example: http://files.mzaweb.com/image/33350l1J3I0M ) it'll work like you're asking... right? (see http://files.mzaweb.com/image/2u2e103F0i2L )

**Comment by cheeselouise** [comment]
ah, I'd left the middle template. Great, and thanks. That fixed it

**Comment by MZAWeb** [comment]
Cool
